# https://packit.dev/docs/configuration/

specfile_path: packaging/rpm/fedora/python-sphinxcontrib-chapeldomain.spec

notifications:
  pull_request:
    successful_build: true

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-x86_64
