name: Bump version

on:
  workflow_dispatch:

jobs:
  bump-patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Exit if branch exists
      run: |
        BRANCH_NAME="update-version"
        if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
          echo "Branch $BRANCH_NAME already exists."
          exit 1
        fi
    - name: Create a new branch
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b update-version
        git push --set-upstream origin update-version
    - name: Bump Version
      run: |
        ./util/bump-version.sh
        git commit -am "Bump version for next release"
        git push
    - name: create pull request
      run: >
        gh pr create
        -B main
        -H update-version
        --title 'Bump version for next release'
        --body 'Bump the version in prep for next release'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
